export const API_ROUTES = {
  AUTH_MAGIC_LINK: "/api/v1/auth/magic-link",
  AUTH_VERIFY: "/api/v1/auth/verify",
  HOGAR: "/api/v1/hogar",
  HOGAR_JOIN: "/api/v1/hogar/join",
  INVENTORY: "/api/v1/inventory",
  INVENTORY_ADD: "/api/v1/inventory/add",
  INVENTORY_REMOVE: "/api/v1/inventory/remove",
  SHOPPING_LIST: "/api/v1/shopping-list",
  SHOPPING_RESTOCK: "/api/v1/shopping-list/restock",
  PRICES: "/api/v1/prices",
  EVENTS: "/api/v1/events_stock",
  PUSH_VAPID_KEY: "/api/v1/push/vapid-key",
  PUSH_SUBSCRIBE: "/api/v1/push/subscribe",
};
